// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package Login

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ThirdpartyRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Mode                 uint32   `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThirdpartyRequest) Reset()         { *m = ThirdpartyRequest{} }
func (m *ThirdpartyRequest) String() string { return proto.CompactTextString(m) }
func (*ThirdpartyRequest) ProtoMessage()    {}
func (*ThirdpartyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_18d67d46b527bfee, []int{0}
}
func (m *ThirdpartyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThirdpartyRequest.Unmarshal(m, b)
}
func (m *ThirdpartyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThirdpartyRequest.Marshal(b, m, deterministic)
}
func (dst *ThirdpartyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThirdpartyRequest.Merge(dst, src)
}
func (m *ThirdpartyRequest) XXX_Size() int {
	return xxx_messageInfo_ThirdpartyRequest.Size(m)
}
func (m *ThirdpartyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ThirdpartyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ThirdpartyRequest proto.InternalMessageInfo

func (m *ThirdpartyRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ThirdpartyRequest) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

type ThirdpartyResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sex                  bool     `protobuf:"varint,3,opt,name=sex,proto3" json:"sex,omitempty"`
	Headimgurl           string   `protobuf:"bytes,4,opt,name=headimgurl,proto3" json:"headimgurl,omitempty"`
	Gold                 uint64   `protobuf:"varint,5,opt,name=gold,proto3" json:"gold,omitempty"`
	Token                string   `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThirdpartyResponse) Reset()         { *m = ThirdpartyResponse{} }
func (m *ThirdpartyResponse) String() string { return proto.CompactTextString(m) }
func (*ThirdpartyResponse) ProtoMessage()    {}
func (*ThirdpartyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_18d67d46b527bfee, []int{1}
}
func (m *ThirdpartyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThirdpartyResponse.Unmarshal(m, b)
}
func (m *ThirdpartyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThirdpartyResponse.Marshal(b, m, deterministic)
}
func (dst *ThirdpartyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThirdpartyResponse.Merge(dst, src)
}
func (m *ThirdpartyResponse) XXX_Size() int {
	return xxx_messageInfo_ThirdpartyResponse.Size(m)
}
func (m *ThirdpartyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ThirdpartyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ThirdpartyResponse proto.InternalMessageInfo

func (m *ThirdpartyResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ThirdpartyResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ThirdpartyResponse) GetSex() bool {
	if m != nil {
		return m.Sex
	}
	return false
}

func (m *ThirdpartyResponse) GetHeadimgurl() string {
	if m != nil {
		return m.Headimgurl
	}
	return ""
}

func (m *ThirdpartyResponse) GetGold() uint64 {
	if m != nil {
		return m.Gold
	}
	return 0
}

func (m *ThirdpartyResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*ThirdpartyRequest)(nil), "Login.ThirdpartyRequest")
	proto.RegisterType((*ThirdpartyResponse)(nil), "Login.ThirdpartyResponse")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_login_18d67d46b527bfee) }

var fileDescriptor_login_18d67d46b527bfee = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x8d, 0xdb, 0x96, 0xdd, 0x11, 0x41, 0x07, 0x91, 0xe8, 0x41, 0x42, 0x4f, 0x39, 0xf5,
	0xa0, 0x47, 0x8f, 0x7b, 0x12, 0x04, 0x25, 0xf8, 0x07, 0xaa, 0x19, 0xba, 0xc5, 0x36, 0xa9, 0x49,
	0x0a, 0xfa, 0x5f, 0xfc, 0xb1, 0x92, 0xe9, 0x22, 0x0b, 0x7a, 0xfb, 0xde, 0x9b, 0xc9, 0x23, 0x6f,
	0xe0, 0x64, 0xf0, 0x5d, 0xef, 0x9a, 0x29, 0xf8, 0xe4, 0xb1, 0x7c, 0xcc, 0xa2, 0xbe, 0x87, 0xf3,
	0x97, 0x5d, 0x1f, 0xec, 0xd4, 0x86, 0xf4, 0x65, 0xe8, 0x63, 0xa6, 0x98, 0x10, 0xa1, 0x78, 0xf3,
	0x96, 0xa4, 0x50, 0x42, 0x6f, 0x0c, 0x73, 0xf6, 0xc6, 0xec, 0x1d, 0x2b, 0xa1, 0x4f, 0x0d, 0x73,
	0xfd, 0x2d, 0x00, 0x0f, 0x5f, 0xc7, 0xc9, 0xbb, 0x48, 0x78, 0x09, 0xd5, 0x1c, 0x29, 0x3c, 0xd8,
	0x7d, 0xc0, 0x5e, 0xe5, 0x08, 0xd7, 0x8e, 0x4b, 0xc4, 0xc6, 0x30, 0xe3, 0x19, 0xac, 0x22, 0x7d,
	0xca, 0x95, 0x12, 0x7a, 0x6d, 0x32, 0xe2, 0x0d, 0xc0, 0x8e, 0x5a, 0xdb, 0x8f, 0xdd, 0x1c, 0x06,
	0x59, 0xf0, 0xee, 0x81, 0x93, 0x53, 0x3a, 0x3f, 0x58, 0x59, 0x2a, 0xa1, 0x0b, 0xc3, 0x8c, 0x17,
	0x50, 0x26, 0xff, 0x4e, 0x4e, 0x56, 0xbc, 0xbe, 0x88, 0xdb, 0x27, 0x58, 0x73, 0x49, 0xf3, 0xbc,
	0xc5, 0x2d, 0x40, 0xfa, 0xfd, 0x29, 0xca, 0x86, 0x07, 0xcd, 0x9f, 0xea, 0xd7, 0x57, 0xff, 0x4c,
	0x96, 0x5a, 0xf5, 0xd1, 0x6b, 0xc5, 0xa7, 0xbb, 0xfb, 0x09, 0x00, 0x00, 0xff, 0xff, 0x77, 0x3b,
	0xe4, 0x8e, 0x49, 0x01, 0x00, 0x00,
}
